services:
  mysql_db:
    image: mysql:8.0.42
    container_name: ${CONTAINER_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - mysql-server
    tty: true

volumes:
    db_mysql:

networks:
    mysql-server:
        driver: bridge